import { getServerSession } from "next-auth/next";
import dbConnect from "@/lib/mongoose";
import { authOptions } from "../../auth/[...nextauth]/route";
import { NextResponse } from "next/server";
import Message from "@/models/message";

export async function POST(req: Request) {
  try {
    const session = await getServerSession(authOptions);

    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    await dbConnect();

    const { chatId, content, role } = await req.json();

    console.log(content, chatId, role, "req body");

    // Store message with preserved newlines and HTML
    const message = await Message.create({
      chatId,
      content: content
        .replace(/\n/g, "\\n")
        // Don't escape HTML - we'll trust the content since it's generated by our system
        .replace(/\\/g, "\\\\"), // Only escape backslashes,
      role,
    });

    return NextResponse.json({ messageId: message._id });
  } catch (error: any) {
    console.error(error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}

// get last message
export const GET = async (req: Request) => {
  try {
    const session = await getServerSession(authOptions);

    if (!session) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    await dbConnect();

    const { chatId } = await req.json();

    const lastMessage = await Message.findOne({ chatId })
      .sort({ createdAt: -1 })
      .limit(1);

    return NextResponse.json(lastMessage);
  } catch (error: any) {
    console.error(error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
};